---
# tasks file for lighthouse-role
- name: Install EPEL
  become: true
  ansible.builtin.yum:
    name: "epel-release"
    state: present
- name: Install Nginx & Git
  become: true
  ansible.builtin.yum:
    name:
      - nginx
      - git
    state: present
  notify: reload-nginx
- name: Nginx config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0755
  notify: reload-nginx
- name: Autorun Nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
#  become: true
#  ansible.builtin.yum:
#    name: "firewalld"
#    state: latest
#- name: Start FireWall
#  become: true
#  ansible.builtin.systemd:
#    name: firewalld
#    state: started
#- name: Upgrade FireWall
#  become: true
#  ansible.builtin.command:
#    cmd: "{{ item }}"
#  with_items:
#    - firewall-cmd --zone=public --permanent --add-service=http
#    - firewall-cmd --zone=public --permanent --add-service=https
#    - firewall-cmd --reload
- name: Lighthose copy from git
  git:
   repo: "{{ lighthouse_vcs }}"
   version: master
   dest: "{{ lighthouse_location_dir }}"
- name: lighthouse config
  become: true
  template:
   src: lighthouse.conf.j2
   dest: /etc/nginx/conf.d/default.conf
   mode: 0755
  notify: reload-nginx